### ISSUE TITLE
Node/solo miner error

### ISSUE THREAD

**Issue by image28** [Pttn/rieMiner#25]
Getting an error when I try to solo mine on my node
fetchWork: invalid GetBlockTemplate response! Ensure that you use Riecoin Core 0.20+ and that it is properly configured and synced!
Unable to get mining data from the server :| !
Failure :| ! Check your connection, configuration or credentials. Retry in 10 s...

Was working yesterday ( did have the node offline for a few hours )

**Comment by Pttn** [comment]
There is certainly an issue at your end, others don't have any problem.
You can ask for further help on Discord if needed, but then be sure to give the full details (configuration files, what you tried to do,...), else we cannot help...
